### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by matias-gonz**

### CODE REVIEW

**Review by ilitteri — APPROVED** [review]
Looks good! Let's add the Go jobs in another PR

**Review by ilitteri — CHANGES_REQUESTED** [review]
Sorry, I just realized, we don't have a `clippy` target in our Makefile. Let's use `cargo clippy --all-targets --all-features -- -D warnings` for it.

**Comment by matias-gonz** [comment]
Clippy fails with:
```
error: features "bn254" and "bls12_381" cannot be used together
  --> /Users/matiasgonzalez/.cargo/git/checkouts/acvm-f3986237eed0311f/373c18f/acir_field/src/lib.rs:30:13
   |
30 |             compile_error!(concat!("features \"", $first, "\" and \"", $rest, "\" cannot be used together"));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
37 | assert_unique_feature!("bn254", "bls12_381");
   | -------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `assert_unique_feature` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `acir_field` due to previous error
```

**Comment by ilitteri** [comment]
> Clippy fails with:
> 
> ```
> error: features "bn254" and "bls12_381" cannot be used together
>   --> /Users/matiasgonzalez/.cargo/git/checkouts/acvm-f3986237eed0311f/373c18f/acir_field/src/lib.rs:30:13
>    |
> 30 |             compile_error!(concat!("features \"", $first, "\" and \"", $rest, "\" cannot be used together"));
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 37 | assert_unique_feature!("bn254", "bls12_381");
>    | -------------------------------------------- in this macro invocation
>    |
>    = note: this error originates in the macro `assert_unique_feature` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error: could not compile `acir_field` due to previous error
> ```

I see, let's try with `cargo clippy --all-targets --features=bn254,bls12_381 -- -D warnings`

**Comment by matias-gonz** [comment]
I see the same error 😢

**Comment by ilitteri** [comment]
> I see the same error 😢

Ok, let's run clippy twice like this:

```sh
cargo clippy --all-targets --features bn254 -- -D warnings
cargo clippy --all-targets --features bls12_381 -- -D warnings
```

**Comment by matias-gonz** [comment]
`bn254` works but `bls12_381 ` throws same error

**Comment by ilitteri** [comment]
> `bn254` works but `bls12_381 ` throws same error

Let's use `cargo clippy --all-targets -- -D warnings` and add a comment explaining that this should be revisited because no all the features are being checked. Add the comment at the top of the file because the same happens with the other jobs.

**Review by ilitteri — APPROVED** [review]
LGTM. We can merge after the conflicts are solved.

**Review by ilitteri — APPROVED** [review]

**Pull request merged**
